Repository dataware-tools/api-meta-store, pull requests merged in 2021-07, with the labels that each got.

#40 Use GitHub-hosted runners
  .github/workflows/build_and_test.yml
Labels: approved

#41 Fix the bug that searching with `=` fails
  api/utils.py
  test/test_utils.py
Labels: approved, size/S

#42 Bump pydtk to `v0.1.2`
  pyproject.toml
Labels: approved, size/XS

#43 Add permission check for list-database resource
  api/databases.py
  api/utils.py
  test/test_databases.py
Labels: approved, lgtm, size/M

#45 Fix the bug that no records were returned when record_id was numeric value
  api/utils.py
Labels: approved, size/XS

#46 Fix the bug that the permission-client fails to init with the default env-var
  api/utils.py
Labels: approved, size/XS

#48 Bump pydtk to `^0.1.4`
  poetry.lock
  pyproject.toml
Labels: approved, size/XL

#47 Fix bug that PATCH /databases/{database_id} requires database_id
  api/databases.py
  test/test_databases.py
Labels: approved, lgtm, size/XS

#50 Support specify sort order
  api/records.py
  test/test_records.py
Labels: approved, lgtm, size/M

#51 Fix the bug that boolean was not treated properly when searching
  api/utils.py
  test/test_utils.py
Labels: approved, lgtm, size/S
