Repository dataware-tools/api-meta-store, pull requests merged in 2021-08, with the labels that each got.

#53 Fix error messages for easy understanding
  api/config.py
  api/databases.py
  api/files.py
  api/records.py
  api/utils.py
Labels: approved, lgtm, size/M

#52 Support case-insensitive keyword search
  api/utils.py
  test/test_records.py
Labels: approved, lgtm, size/XS

#54 Use permission logics of api-helper-python
  api/config.py
  api/databases.py
  api/files.py
  api/records.py
  api/utils.py
  poetry.lock
  pyproject.toml
  test/test_utils.py
Labels: approved, size/XL, lgtm
